### ISSUE TITLE
struct internalType for array

### ISSUE THREAD

**Issue by esaulpaugh** [gnidan/abi-to-sol#121]
I noticed that the default example JSON shows a `tuple[]` type with an `internalType` of `struct Magic`. Is this correct? It seems inconsistent. I would expect something more like `struct Magic[]`.

    {
        "type": "event",
        "name": "Magic",
        "inputs": [
          {
            "internalType": "struct Magic",
            "name": "magic",
            "type": "tuple[]",
            "indexed": false,
            "components": [
              {
                "name": "magic",
                "type": "string"
              }
            ]
          }
        ],
        "anonymous": false
    }

**Comment by gnidan** [comment]
Looks like you're correct! Thanks for raising this! Seems like that example also doesn't compile these days, due to a shadowed "Magic" declaration (I had to change the event name to `MagicHappened`)

I'll PR this fix later today unless you want the contributor credit :)

**Comment by esaulpaugh** [comment]
Sounds good. Thanks for the quick response.

**Comment by gnidan** [comment]
(Reopening this so I don't forget. I'll close when it's fixed :)

**Comment by gnidan** [comment]
Alright, fix is now deployed! Thanks again!
