### ISSUE TITLE
make autogenerated from abi comment optional via cli flag

### ISSUE THREAD

**Issue by jorijnsmit** [gnidan/abi-to-sol#68]
think this is the relevant line: https://github.com/gnidan/abi-to-sol/blob/e37636a9812249b536a9bd0e4ab5c5947ad8c3ee/packages/abi-to-sol/src/solidity.ts#L147-L154

would need some if statement based on a boolean passed through the cli.

top comment might then also need to be rephrased slightly.

**Comment by gnidan** [comment]
I was wondering if anyone would ever want this! 

should be easy to add, just a bunch of stringing a new option through the code. CLI options are configured right in the [main executable file](https://github.com/gnidan/abi-to-sol/blob/develop/packages/abi-to-sol/bin/abi-to-sol.ts) via that DSL.. just a matter of adding the new flag everywhere that `license` and `solidityVersion` appear, all the way down to those `generate` functions.

(ps mad props for using the CLI. I know I made the web-ui, but c'mon the target audience for this tool is like 80% degens... degens of all people should know to run their software locally, dang it :)

**Comment by gnidan** [comment]
Just released this in v0.6.1! Thanks for the suggestion @jorijnsmit 🙇
